# Generated by Django 4.1.6 on 2023-06-26 08:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0002_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='key',
            field=models.CharField(default=uuid.uuid4, max_length=40, primary_key=True, serialize=False, unique=True),
        ),
    ]
