# Generated by Django 4.1.6 on 2023-06-26 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0003_alter_token_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='key',
            field=models.CharField(max_length=40, primary_key=True, serialize=False, unique=True),
        ),
    ]
