# Generated by Django 4.1.6 on 2023-07-06 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_details', '0003_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
